### ISSUE TITLE
general-core is broken

### ISSUE THREAD

**Issue by XPMUser** [XPMUser/Website-Tester#10]
### What went wrong?

general-core is still broken

### How can I reproduce this?

Play the game

### What did the console output?

phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: shine-corner2
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: shine-corner3
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:9 
 Uncaught TypeError: Cannot read properties of null (reading 'sourceSizeW')
    at b.TilingSprite.generateTilingTexture (phaser.min.js:9:13103)
    at b.TilingSprite._renderCanvas (phaser.min.js:9:11945)
    at b.DisplayObjectContainer._renderCanvas (phaser.min.js:7:3486)
    at b.DisplayObjectContainer._renderCanvas (phaser.min.js:7:3486)
    at b.DisplayObjectContainer._renderCanvas (phaser.min.js:7:3486)
    at b.CanvasRenderer.renderDisplayObject (phaser.min.js:8:25973)
    at b.CanvasRenderer.render (phaser.min.js:8:25295)
    at c.Game.updateRender (phaser.min.js:11:29391)
    at c.Game.update (phaser.min.js:11:28713)
    at c.RequestAnimationFrame.updateRAF (phaser.min.js:17:14931)
phaser.min.js:14 
 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty
phaser.min.js:19 
 Phaser.Cache.getImage: Key "core" not found in Cache.
phaser.min.js:18 
 Cannot set frameName: empty

**Comment by XPMUser** [comment]
Try doing what I did with zone-house.json for pde2015, but for general-core.json for pde1.51.0.
